version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:1-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tokenkeeper
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
